### ISSUE TITLE
Login/Register form validation

### ISSUE THREAD

**Issue by turnervink** [turnervink/vanpeaks#34]

**Comment by turnervink** [comment]
Looks great! However in 13d54b7388b9eaf372d8b901b9f743ef38762295 when an error occurs in the login form the popup message shifts the form elements over due to its length.

![screen shot 2017-03-14 at 11 08 27 am](https://cloud.githubusercontent.com/assets/11531685/23915530/9d7dec88-08a6-11e7-82af-908a513e98fd.png)
![screen shot 2017-03-14 at 11 08 31 am](https://cloud.githubusercontent.com/assets/11531685/23915534/a14d2b3a-08a6-11e7-9270-7c16cbbb7077.png)

**Comment by Flinze** [comment]
I pushed a fix, though not 100% if it'll fix it, seems to do with display resolution.

**Comment by turnervink** [comment]
Looks good!
![screen shot 2017-03-14 at 11 50 14 am](https://cloud.githubusercontent.com/assets/11531685/23917386/63fdb5f0-08ac-11e7-86b6-1d769bd2f570.png)
